### ISSUE TITLE
How do I use a shell alias/function in a command?

### ISSUE THREAD

**Issue by idgserpro** [zartsoft/zsft.recipe.cmd#1]
We have a bunch of aliases and functions in "$HOME/.bashrc" files. Since plone.recipe.command only uses `/bin/sh`, we gave zsft.recipe.cmd a shot because we can specify `bash`.

But when I try to use a function named `bootstrap` that is in my `$HOME/.bashrc` (my part in buildout.cfg is named `bootstrap_buildout`), I get:

```
Compiling Python files.
Compiling locale files.
Installing bootstrap_buildout.
bootstrap_buildout: Executing install script
/tmp/tmpIYVHx1/run: linha 3: bootstrap: command not found
While:
  Installing bootstrap_buildout.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/user/.buildout/eggs/zc.buildout-2.9.5-py2.7.egg/zc/buildout/buildout.py", line 2123, in main
    getattr(buildout, command)(args)
  File "/home/user/.buildout/eggs/zc.buildout-2.9.5-py2.7.egg/zc/buildout/buildout.py", line 796, in install
    installed_files = self[part]._call(recipe.install)
  File "/home/user/.buildout/eggs/zc.buildout-2.9.5-py2.7.egg/zc/buildout/buildout.py", line 1553, in _call
    return f()
  File "/home/user/.buildout/eggs/zsft.recipe.cmd-0.4-py2.7.egg/zsft/recipe/cmd/shell.py", line 80, in install
    return self._process('install')
  File "/home/user/.buildout/eggs/zsft.recipe.cmd-0.4-py2.7.egg/zsft/recipe/cmd/shell.py", line 75, in _process
    self._execute(script, env=env, shell=shell, shell_opts=shell_opts)
  File "/home/user/.buildout/eggs/zsft.recipe.cmd-0.4-py2.7.egg/zsft/recipe/cmd/shell.py", line 60, in _execute
    check_call(command, env=env)
  File "/home/user/.pythonz/pythons/CPython-2.7.9/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['bash', '/tmp/tmpIYVHx1/run']' returned non-zero exit status 127
```

Doing `source "$HOME/.bashrc"` doesn't work, the function is still not available. How do I make these functions available?

**Comment by zart** [comment]
As bash(1) manpage explains in INVOCATION section, bashrc files are executed by interactive shell.
You can either provide -i flag to the shell, to force it into interactive mode, or better yet to provide environment variable `BASH_ENV=~/.bashrc` which bash will execute in non-interactive mode.

Frankly, I don't think that depending on locally defined aliases is a good idea but YMMV.
